# Generated by Django 5.2.17 on 2026-09-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_organization_unit'),
        ('organizations', '0002_alter_organizationunit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_units',
            field=models.ManyToManyField(blank=True, related_name='users_m2m_tmp', to='organizations.organizationunit', verbose_name='organization units'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_fk_tmp', to='organizations.organizationunit'),
        ),
    ]
