# Generated by Django 5.2.17 on 2026-09-28 04:10
"""
Data migration: copy each user's existing single organization_unit (FK)
into the new organization_units (M2M) before the FK field is dropped in
the next migration. Reversible so `migrate accounts <earlier>` can undo it.
"""
from django.db import migrations


def copy_fk_to_m2m(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(organization_unit__isnull=True):
        user.organization_units.add(user.organization_unit_id)


def copy_m2m_to_fk(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        first_unit_id = user.organization_units.values_list("id", flat=True).first()
        if first_unit_id is not None:
            user.organization_unit_id = first_unit_id
            user.save(update_fields=["organization_unit"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_organization_units_alter_user_organization_unit'),
    ]

    operations = [
        migrations.RunPython(copy_fk_to_m2m, copy_m2m_to_fk),
    ]
