# Generated by Django 5.2.17 on 2026-09-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_migrate_organization_unit_to_m2m'),
        ('organizations', '0002_alter_organizationunit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization_unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_units',
            field=models.ManyToManyField(blank=True, related_name='users', to='organizations.organizationunit', verbose_name='organization units'),
        ),
    ]
