# Generated by Django 5.2.17 on 2026-09-09 05:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='period year')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='period month')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='gross salary')),
                ('advance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='advance')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='deductions')),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='net salary')),
                ('currency', models.CharField(default='UZS', max_length=8, verbose_name='currency')),
                ('components', models.JSONField(blank=True, default=dict, verbose_name='components')),
                ('is_current', models.BooleanField(default=True, verbose_name='is current')),
                ('revision', models.PositiveIntegerField(default=1, verbose_name='revision')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employees.employee', verbose_name='employee')),
                ('source_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries', to='imports.salaryimport', verbose_name='source import')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
                'ordering': ['-period_year', '-period_month', '-revision'],
                'indexes': [models.Index(fields=['employee', 'period_year', 'period_month'], name='salaries_sa_employe_dedbf1_idx'), models.Index(fields=['period_year', 'period_month'], name='salaries_sa_period__c8854a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee', 'period_year', 'period_month'), name='unique_current_salary_per_period'), models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='salary_month_range'), models.CheckConstraint(condition=models.Q(('gross_salary__gte', 0), ('advance__gte', 0), ('deductions__gte', 0), ('net_salary__gte', 0)), name='salary_non_negative')],
            },
        ),
    ]
