# Generated by Django 5.2.17 on 2026-09-10 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_organization_unit'),
        ('imports', '0002_alter_salaryimport_organization_unit'),
        ('organizations', '0002_alter_organizationunit_code'),
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salary',
            name='unique_current_salary_per_period',
        ),
        migrations.AddField(
            model_name='salary',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='organizations.organizationunit', verbose_name='organization unit'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['organization_unit'], name='salaries_sa_organiz_45f089_idx'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee', 'organization_unit', 'period_year', 'period_month'), name='unique_current_salary_per_period_per_unit'),
        ),
    ]
