# Generated by Django 5.2.17 on 2026-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0004_organization_unit_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='components',
            field=models.JSONField(blank=True, default=list, verbose_name='components'),
        ),
    ]
