# Generated by Django 5.2.17 on 2026-09-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0005_alter_salary_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='payroll_jshshir',
            field=models.CharField(blank=True, max_length=14, verbose_name='payroll JSHSHIR'),
        ),
    ]
