# Generated by Django 5.2.17 on 2026-09-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_telegramcontact_jshshir'),
        ('imports', '0003_alter_salaryimport_uploaded_by'),
        ('organizations', '0002_alter_organizationunit_code'),
        ('salaries', '0006_salary_payroll_jshshir'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salary',
            name='unique_current_salary_per_period_per_unit',
        ),
        migrations.AddField(
            model_name='salary',
            name='payroll_employee_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='payroll employee code'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee', 'organization_unit', 'period_year', 'period_month', 'payroll_employee_code'), name='unique_current_salary_per_period_per_unit_per_code'),
        ),
    ]
