# Generated by Django 5.2.17 on 2026-09-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0007_remove_salary_unique_current_salary_per_period_per_unit_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salary',
            name='salary_non_negative',
        ),
    ]
