# Generated by Django 5.2.17 on 2026-09-19 19:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0008_remove_salary_salary_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='income_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='income tax (NDFL)'),
        ),
        migrations.AddField(
            model_name='salary',
            name='pension_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='pension contribution (INPS)'),
        ),
        migrations.AddField(
            model_name='salary',
            name='social_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='social tax'),
        ),
        migrations.AddField(
            model_name='salary',
            name='union_dues',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='union dues'),
        ),
    ]
