# Generated by Django 5.2.17 on 2026-09-21 11:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0009_salary_income_tax_salary_pension_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='base rate (oklad)'),
        ),
        migrations.AddField(
            model_name='salary',
            name='base_rate_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='base rate payment'),
        ),
        migrations.AddField(
            model_name='salary',
            name='gph_contract_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='GPH contract payment'),
        ),
        migrations.AddField(
            model_name='salary',
            name='honored_railway_worker_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='honored railway worker bonus'),
        ),
        migrations.AddField(
            model_name='salary',
            name='hourly_workers_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='hourly workers bonus'),
        ),
        migrations.AddField(
            model_name='salary',
            name='internal_combination_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='internal combination payment'),
        ),
        migrations.AddField(
            model_name='salary',
            name='meal_compensation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='meal compensation'),
        ),
        migrations.AddField(
            model_name='salary',
            name='mentorship_bonus',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='mentorship bonus'),
        ),
        migrations.AddField(
            model_name='salary',
            name='mortgage_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='mortgage deduction'),
        ),
        migrations.AddField(
            model_name='salary',
            name='paid_services',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='paid services'),
        ),
        migrations.AddField(
            model_name='salary',
            name='position_combination_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='position combination payment'),
        ),
    ]
