# Generated by Django 5.2.17 on 2026-09-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('SALARY_IMPORTED', 'Salary imported'), ('SALARY_MODIFIED', 'Salary modified'), ('SALARY_DELETED', 'Salary deleted'), ('EXCEL_UPLOADED', 'Excel uploaded'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('NOTIFICATION_SENT', 'Notification sent'), ('NOTIFICATION_RESENT', 'Notification resent'), ('ADMIN_CREATED', 'Admin created'), ('PERMISSION_CHANGED', 'Permission changed'), ('TELEGRAM_LINKED', 'Telegram linked'), ('TELEGRAM_UNLINKED', 'Telegram unlinked')], max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action'], name='audit_audit_action_86e815_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
