# Generated by Django 5.2.17 on 2026-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login failed'), ('EMPLOYEE_CREATED', 'Employee created'), ('EMPLOYEE_UPDATED', 'Employee updated'), ('SALARY_IMPORTED', 'Salary imported'), ('SALARY_MODIFIED', 'Salary modified'), ('SALARY_DELETED', 'Salary deleted'), ('EXCEL_UPLOADED', 'Excel uploaded'), ('IMPORT_CONFIRMED', 'Import confirmed'), ('NOTIFICATION_SENT', 'Notification sent'), ('NOTIFICATION_RESENT', 'Notification resent'), ('ADMIN_CREATED', 'Admin created'), ('PERMISSION_CHANGED', 'Permission changed'), ('TELEGRAM_LINKED', 'Telegram linked'), ('TELEGRAM_UNLINKED', 'Telegram unlinked'), ('BRANCH_CREATED', 'Branch created'), ('BRANCH_UPDATED', 'Branch updated'), ('BRANCH_ACTIVATED', 'Branch activated'), ('BRANCH_DEACTIVATED', 'Branch deactivated'), ('BRANCH_DELETED', 'Branch deleted'), ('EMPLOYEE_ACTIVATED', 'Employee activated'), ('EMPLOYEE_DEACTIVATED', 'Employee deactivated'), ('EMPLOYEE_DELETED', 'Employee deleted')], max_length=32),
        ),
    ]
