# Generated by Django 5.2.17 on 2026-09-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=64, unique=True, verbose_name='employee code')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('phone', models.CharField(max_length=32, verbose_name='phone')),
                ('normalized_phone', models.CharField(db_index=True, max_length=20, verbose_name='normalized phone')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='telegram id')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='telegram username')),
                ('telegram_linked_at', models.DateTimeField(blank=True, null=True, verbose_name='telegram linked at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organizations.organizationunit', verbose_name='organization unit')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['normalized_phone'], name='employees_e_normali_259a62_idx'), models.Index(fields=['organization_unit'], name='employees_e_organiz_e5ddac_idx'), models.Index(fields=['telegram_id'], name='employees_e_telegra_1dce9a_idx'), models.Index(fields=['employee_code'], name='employees_e_employe_f8cfea_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization_unit', 'normalized_phone'), name='unique_phone_per_unit')],
            },
        ),
    ]
