# Generated by Django 5.2.17 on 2026-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='normalized phone')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='telegram id')),
                ('telegram_username', models.CharField(blank=True, max_length=255, verbose_name='telegram username')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='first seen at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'telegram contact',
                'verbose_name_plural': 'telegram contacts',
            },
        ),
    ]
