# Generated by Django 5.2.17 on 2026-09-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_telegramcontact'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=64, verbose_name='employee code'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization_unit', 'employee_code'), name='unique_code_per_unit'),
        ),
    ]
