# Generated by Django 5.2.17 on 2026-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_employee_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_phone_per_unit',
        ),
        migrations.RemoveConstraint(
            model_name='employee',
            name='unique_code_per_unit',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='employee code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='normalized_phone',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='normalized phone'),
        ),
    ]
