# Generated by Django 5.2.17 on 2026-09-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_organization_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="tug'ilgan sana"),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='shartnoma turi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, verbose_name="bo'lim"),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='jinsi'),
        ),
        migrations.AddField(
            model_name='employee',
            name='jshshir',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='JSHSHIR'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='passport seria va raqami'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='lavozim'),
        ),
    ]
