# Generated by Django 5.2.17 on 2026-09-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_birth_date_employee_contract_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramcontact',
            name='jshshir',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='JSHSHIR'),
        ),
    ]
