# Generated by Django 5.2.17 on 2026-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_telegramcontact_jshshir'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='telegram id')),
                ('agreed_at', models.DateTimeField(auto_now_add=True, verbose_name='agreed at')),
            ],
            options={
                'verbose_name': 'bot consent',
                'verbose_name_plural': 'bot consents',
            },
        ),
    ]
