# Generated by Django 5.2.17 on 2026-09-09 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='column_mapping', to='organizations.organizationunit')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveSmallIntegerField(verbose_name='period year')),
                ('period_month', models.PositiveSmallIntegerField(verbose_name='period month')),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='file')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('VALID', 'Valid'), ('HAS_ERRORS', 'Has errors'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='UPLOADED', max_length=16, verbose_name='status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='total rows')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='valid rows')),
                ('error_rows', models.PositiveIntegerField(default=0, verbose_name='error rows')),
                ('telegram_linked_count', models.PositiveIntegerField(default=0)),
                ('telegram_unlinked_count', models.PositiveIntegerField(default=0)),
                ('validation_payload', models.JSONField(blank=True, default=dict)),
                ('organization_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='organizations.organizationunit', verbose_name='organization unit')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_imports', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'salary import',
                'verbose_name_plural': 'salary imports',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['organization_unit', 'period_year', 'period_month'], name='imports_sal_organiz_06f68d_idx'), models.Index(fields=['status'], name='imports_sal_status_0b8b68_idx')],
            },
        ),
    ]
