# Generated by Django 5.2.17 on 2026-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('type', models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH', 'Branch')], default='BRANCH', max_length=16, verbose_name='type')),
                ('is_head_office', models.BooleanField(default=False, verbose_name='is head office')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'organization unit',
                'verbose_name_plural': 'organization units',
                'ordering': ['-is_head_office', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_head_office', True)), fields=('is_head_office',), name='unique_head_office')],
            },
        ),
    ]
