# Generated by Django 5.2.17 on 2026-09-09 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('salaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='telegram id')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='telegram message id')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by user'), ('RETRYING', 'Retrying'), ('TELEGRAM_NOT_CONNECTED', 'Telegram not connected')], default='PENDING', max_length=32, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='employees.employee')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to='salaries.salary')),
            ],
            options={
                'verbose_name': 'telegram message',
                'verbose_name_plural': 'telegram messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='notificatio_status_9c4799_idx'), models.Index(fields=['telegram_id'], name='notificatio_telegra_6b46dd_idx'), models.Index(fields=['employee'], name='notificatio_employe_921c3a_idx'), models.Index(fields=['salary'], name='notificatio_salary__520d1d_idx')],
                'constraints': [models.UniqueConstraint(fields=('salary', 'employee'), name='unique_message_per_salary_employee')],
            },
        ),
    ]
