# Generated by Django 5.2.17 on 2026-09-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by user'), ('RETRYING', 'Retrying'), ('TELEGRAM_NOT_CONNECTED', 'Telegram not connected'), ('JSHSHIR_MISMATCH', 'JSHSHIR mismatch')], default='PENDING', max_length=32, verbose_name='status'),
        ),
    ]
