# Generated by Django 5.2.17 on 2026-09-16 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_telegramcontact_jshshir'),
        ('notifications', '0003_alter_telegrammessage_status'),
        ('organizations', '0002_alter_organizationunit_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='organizations.organizationunit', verbose_name='organization unit')),
            ],
            options={
                'verbose_name': 'broadcast message',
                'verbose_name_plural': 'broadcast messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='telegram id')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='telegram message id')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked by user'), ('RETRYING', 'Retrying'), ('TELEGRAM_NOT_CONNECTED', 'Telegram not connected'), ('JSHSHIR_MISMATCH', 'JSHSHIR mismatch')], default='PENDING', max_length=32, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.broadcastmessage')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_recipients', to='employees.employee')),
            ],
            options={
                'verbose_name': 'broadcast recipient',
                'verbose_name_plural': 'broadcast recipients',
                'indexes': [models.Index(fields=['status'], name='notificatio_status_808a8d_idx'), models.Index(fields=['broadcast'], name='notificatio_broadca_a4519f_idx')],
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'employee'), name='unique_broadcast_recipient')],
            },
        ),
    ]
